### ISSUE TITLE
Knob stays in "Waiting for home assistant sync"

### ISSUE THREAD

**Issue by mjkl-gh** [SeedLabs-it/smartknob-home-assistant-integration#40]
When connecting my new knob to home assistant it stays waiting for the sync

when looking at the logs these errors are found:

```
Exception in async_init_received when handling msg on 'smartknob/init': '{"id":"00000768","mac_address":"EC:DA:3B:61:6D:A0","data":{"model":"SmartKnob DevKit v0.1","version":"0.3.1","manufacturer":"Seedlabs"}}' Traceback (most recent call last): File "/config/custom_components/smartknob/mqtt.py", line 162, in async_init_received sw_version=data["firmware_version"], ~~~~^^^^^^^^^^^^^^^^^^^^ KeyError: 'firmware_version'
Exception in async_init_received when handling msg on 'smartknob/init': '{"id":"00002717","mac_address":"EC:DA:3B:61:6D:A0","data":{"model":"SmartKnob DevKit v0.1","version":"0.3.1","manufacturer":"Seedlabs"}}' Traceback (most recent call last): File "/config/custom_components/smartknob/mqtt.py", line 162, in async_init_received sw_version=data["firmware_version"], ~~~~^^^^^^^^^^^^^^^^^^^^ KeyError: 'firmware_version'
Exception in async_init_received when handling msg on 'smartknob/init': '{"id":"00004E2F","mac_address":"EC:DA:3B:61:6D:A0","data":{"model":"SmartKnob DevKit v0.1","version":"0.3.1","manufacturer":"Seedlabs"}}' Traceback (most recent call last): File "/config/custom_components/smartknob/mqtt.py", line 162, in async_init_received sw_version=data["firmware_version"], ~~~~^^^^^^^^^^^^^^^^^^^^ KeyError: 'firmware_version'
Exception in async_init_received when handling msg on 'smartknob/init': '{"id":"00007544","mac_address":"EC:DA:3B:61:6D:A0","data":{"model":"SmartKnob DevKit v0.1","version":"0.3.1","manufacturer":"Seedlabs"}}' Traceback (most recent call last): File "/config/custom_components/smartknob/mqtt.py", line 162, in async_init_received sw_version=data["firmware_version"], ~~~~^^^^^^^^^^^^^^^^^^^^ KeyError: 'firmware_version'
Exception in async_init_received when handling msg on 'smartknob/init': '{"id":"00009C5D","mac_address":"EC:DA:3B:61:6D:A0","data":{"model":"SmartKnob DevKit v0.1","version":"0.3.1","manufacturer":"Seedlabs"}}' Traceback (most recent call last): File "/config/custom_components/smartknob/mqtt.py", line 162, in async_init_received sw_version=data["firmware_version"], ~~~~^^^^^^^^^^^^^^^^^^^^ KeyError: 'firmware_version'
```

I presume the key `firmware_version` got changed to `version` somewhere between 0.2.0 and 0.3.1, but the home assistant integration was not updated

If i can make time over the weekend, i'll gladly take a closer look at whats going wrong.

note: I received my knob with version 0.3.1 which according to the firmware page is a prerelease version

**Comment by carlhampuswall** [comment]
Should be resolved with latest release [v0.2.2](https://github.com/SeedLabs-it/smartknob-home-assistant-integration/releases/tag/0.2.2)
